package com.sebet.cartservice.cart.enums.store_basket_issues;

public enum StoreBasketIssueCode {
    MINIMUM_ORDER_NOT_REACHED,
    DELIVERY_UNAVAILABLE,
    DELIVERY_ADDRESS_MISSING,
    DELIVERY_FEE_UNAVAILABLE,
    DELIVERY_NOT_AVAILABLE,
    SCHEDULED_SLOT_EXPIRED,
    SCHEDULED_SLOT_UNAVAILABLE,
    PROMOTION_SERVICE_UNAVAILABLE,
}
