package com.sebet.cartservice.cart.enums.store_basket_issues;

public enum StoreBasketIssueReason {
    STORE_CLOSED,
    STORE_TEMPORARILY_DISABLED,
  STORE_NOT_ACCEPTING_ORDERS,
    NO_RIDERS_AVAILABLE,
     DELIVERY_TEMPORARILY_DISABLED,
     BAD_WEATHER,
   OUTSIDE_DELIVERY_ZONE,
    PROMO_NOT_VALID_FOR_STORE,
 PROMO_NOT_VALID_FOR_CUSTOMER,
PROMO_USAGE_LIMIT_REACHED
}
