spring:
  application:
    name: order-service

  jpa:
    open-in-view: false

  kafka:
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

order-service:
  kafka:
    checkout-events:
      topic: checkout-events
      group-id: order-service
      auto-startup: false
      dlt-topic: checkout-events.DLT
      validate-topics: false
      retry:
        initial-interval-ms: 1000
        multiplier: 2.0
        max-interval-ms: 10000
        max-attempts: 3
