package com.sebet.cartservice.cart.enums;

public enum ItemIssuesCode {
    PRICE_CHANGED,
    OUT_OF_STOCK,
    INSUFFICIENT_STOCK,
    PRODUCT_UNAVAILABLE,
    PRODUCT_NOT_FOUND,
    PRODUCT_INACTIVE,
    PRODUCT_NOT_SELLABLE,
    QUANTITY_BELOW_MINIMUM,
    QUANTITY_ABOVE_MAXIMUM,
    INVENTORY_NOT_FOUND,
    INVENTORY_QUANTITY_UNKNOWN,
    INVALID_QUANTITY
}
